apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: shipping-service
  name: shipping-service
spec:
  ports:
    - name: 3005-3005
      port: 3005
      protocol: TCP
      targetPort: 3005
      nodePort: 30157
  selector:
    app: shipping-service
  type: NodePort
status:
  loadBalancer: {}
