apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: order-service
    spec:
      containers:
      - image: order-service:latest
        name: order-service
        imagePullPolicy: Never
        resources: {}
        env:
          - name: DB_HOST_NAME
            value: "mongo-db"
          - name: KAFKA_BOOTSTRAP_SERVER
            value: "192.168.99.1:29092"
status: {}
