apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: order-service
  name: order-service
spec:
  ports:
    - name: 3003-3003
      port: 3003
      protocol: TCP
      targetPort: 3003
      nodePort: 30011
  selector:
    app: order-service
  type: NodePort
status:
  loadBalancer: {}
