apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payment-service
  name: payment-service
spec:
  ports:
    - name: 3004-3004
      port: 3004
      protocol: TCP
      targetPort: 3004
      nodePort: 30015
  selector:
    app: payment-service
  type: NodePort
status:
  loadBalancer: {}
