apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: auth-service
  name: auth-service
spec:
  ports:
    - name: 3002-3002
      port: 3002
      protocol: TCP
      targetPort: 3002
      nodePort: 30007
  selector:
    app: auth-service
  type: NodePort
status:
  loadBalancer: {}
