apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: shopping-service
  name: shopping-service
spec:
  ports:
    - name: 3000-3000
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30121
  selector:
    app: shopping-service
  type: NodePort
status:
  loadBalancer: {}
