apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-db
  name: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-db
    spec:
      containers:
      - image: mongo:latest
        name: mongo-db
        resources: {}
status: {}
