apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: user-service
  name: user-service
spec:
  ports:
    - name: 3001-3001
      port: 3001
      protocol: TCP
      targetPort: 3001
      nodePort: 30087
  selector:
    app: user-service
  type: NodePort
status:
  loadBalancer: {}
